Various updates
onmetal/metalbond pull request #55
Opened 2023-02-01 09:23 UTC by FlorinPeter

# Proposed Changes

- added Dockerfile
- added prefer network handling
- fix nil pointer dereference
- fix error message

2023-02-01 11:51 UTC, afritzler requested changes
Some small changes. In general would like to see some test cases in the `metalbond` project.

Maybe @byteocean can also have a look at this PR as I can not judge how the route table configuration will affect our current setup.

2023-02-01 11:51 UTC, afritzler commented on Dockerfile
> +COPY . .
I would not copy all the content but just the relevant files.

2023-02-01 11:51 UTC, afritzler commented on Dockerfile
> +FROM debian:bookworm
I would recommend using the `slim` version as a base image.

2023-02-01 11:51 UTC, afritzler commented on netlink.go
> +	if c.config.PreferNetwork != nil {
This code looks very similar to the one above. Can we move this into a helper method?

2023-02-06 17:21 UTC, MalteJ commented
puh, that's a huge PR touching a lot of things.

What's preferNetwork?

2023-02-06 17:27 UTC, MalteJ commented
Sorry, this PR is too big, I cannot understand it.

2023-02-06 18:07 UTC, FlorinPeter commented
@MalteJ then let's go together thru the changes

2023-02-07 08:58 UTC, closed without merging